"""
Anticloud Single Binary Builder
Wraps any Python project into a single portable executable via PyInstaller.
Embeds PAX model path, AIOSS genesis, version, and build metadata.
Deterministic build hash recorded in provenance chain.
"""
import hashlib, json, os, platform, subprocess, sys, time
from pathlib import Path
from typing import List, Optional


BUILD_MANIFEST_SCHEMA = {
    "project":      str,
    "version":      str,
    "entry_point":  str,
    "aioss_genesis": str,
    "pax_model":    str,
    "build_ts":     float,
    "builder_node": str,
    "python_ver":   str,
    "platform":     str,
}

GENESIS = "8b4a8a4f6312dfbe885de8280716985637c163fd2a4b5590341d56db1cc4e560"


def _sha3_file(path: str) -> str:
    h = hashlib.sha3_256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _sha3_dir(path: str) -> str:
    """Deterministic hash of all source files in a directory."""
    h = hashlib.sha3_256()
    for root, dirs, files in os.walk(path):
        dirs.sort()
        for fname in sorted(files):
            if fname.endswith((".pyc", ".pyo")):
                continue
            fpath = os.path.join(root, fname)
            rel   = os.path.relpath(fpath, path)
            h.update(rel.encode())
            h.update(_sha3_file(fpath).encode())
    return h.hexdigest()


def generate_build_manifest(project: str, version: str, entry_point: str,
                             src_dir: str) -> dict:
    return {
        "project":       project,
        "version":       version,
        "entry_point":   entry_point,
        "aioss_genesis": GENESIS,
        "pax_model":     "PAX L5 Narrow L2 General 27B",
        "build_ts":      time.time(),
        "builder_node":  platform.node(),
        "python_ver":    sys.version,
        "platform":      platform.platform(),
        "source_hash":   _sha3_dir(src_dir),
    }


def write_version_file(manifest: dict, out_path: str) -> None:
    """Write _anticloud_version.py to be embedded in binary."""
    lines = [
        "# Auto-generated by Anticloud single_binary.py — do not edit",
        f'PROJECT       = {manifest["project"]!r}',
        f'VERSION       = {manifest["version"]!r}',
        f'PAX_MODEL     = {manifest["pax_model"]!r}',
        f'AIOSS_GENESIS = {manifest["aioss_genesis"]!r}',
        f'BUILD_TS      = {manifest["build_ts"]}',
        f'SOURCE_HASH   = {manifest["source_hash"]!r}',
        f'PLATFORM      = {manifest["platform"]!r}',
    ]
    Path(out_path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def build(project: str, version: str, entry_point: str,
          src_dir: str, dist_dir: str,
          extra_data: Optional[List[str]] = None,
          hidden_imports: Optional[List[str]] = None,
          onefile: bool = True) -> dict:
    """
    Build single binary. Returns build result dict with binary path + hash.
    Requires PyInstaller: pip install pyinstaller
    """
    src_dir  = Path(src_dir)
    dist_dir = Path(dist_dir)
    dist_dir.mkdir(parents=True, exist_ok=True)

    manifest = generate_build_manifest(project, version, entry_point, str(src_dir))
    version_file = src_dir / "_anticloud_version.py"
    write_version_file(manifest, str(version_file))

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--distpath", str(dist_dir),
        "--workpath", str(dist_dir / "build_work"),
        "--specpath", str(dist_dir),
        "--name", project,
        "--clean",
        "--noconfirm",
    ]
    if onefile:
        cmd.append("--onefile")
    for d in (extra_data or []):
        cmd += ["--add-data", d]
    for h in (hidden_imports or []):
        cmd += ["--hidden-import", h]
    cmd.append(str(src_dir / entry_point))

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        return {
            "success": False,
            "error": result.stderr[-2000:],
            "manifest": manifest,
        }

    # Find built binary
    suffix = ".exe" if platform.system() == "Windows" else ""
    binary = dist_dir / f"{project}{suffix}"
    if not binary.exists():
        return {"success": False, "error": "Binary not found after build", "manifest": manifest}

    binary_hash = _sha3_file(str(binary))
    manifest["binary_hash"] = binary_hash
    manifest["binary_path"] = str(binary)

    # Write manifest JSON next to binary
    manifest_path = dist_dir / f"{project}_build_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    return {
        "success": True,
        "binary": str(binary),
        "binary_hash": binary_hash,
        "manifest": manifest,
        "manifest_path": str(manifest_path),
    }


def verify_binary(binary_path: str, manifest_path: str) -> dict:
    """Verify binary hash matches manifest. Deterministic build check."""
    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)
    actual_hash = _sha3_file(binary_path)
    match = actual_hash == manifest.get("binary_hash", "")
    return {
        "binary":   binary_path,
        "expected": manifest.get("binary_hash"),
        "actual":   actual_hash,
        "match":    match,
        "project":  manifest.get("project"),
        "version":  manifest.get("version"),
    }
